head -n 49 ../collector/log-alexa/50/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/50/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/50/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/50/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/32/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/32/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/32/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/35/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/35/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/35/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/51/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/51/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/51/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/58/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/58/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/58/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/34/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/34/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/34/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/33/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/33/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/33/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/20/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/20/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/20/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/18/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/18/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/18/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/9/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/9/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/9/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/11/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/11/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/11/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/7/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/7/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/7/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/29/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/29/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/29/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/16/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/16/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/16/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/42/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/42/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/42/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/6/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/6/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/6/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/17/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/17/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/17/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/1/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/1/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/1/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/19/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/19/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/19/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/26/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/26/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/26/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/21/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/21/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/21/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/44/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/44/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/44/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/43/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/43/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/43/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/38/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/38/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/38/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/36/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/36/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/36/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/54/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/54/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/54/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/53/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/53/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/53/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/30/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/30/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/30/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/37/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/37/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/37/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/52/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/52/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/52/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/46/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/46/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/46/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/41/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/41/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/41/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/48/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/48/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/48/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/4/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/4/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/4/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/15/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/15/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/15/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/3/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/3/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/3/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/12/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/12/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/12/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/49/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/49/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/49/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/40/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/40/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/40/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/47/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/47/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/47/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/13/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/13/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/13/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/5/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/5/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/5/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/14/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/14/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/14/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/22/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/22/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-alexa/22/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/32/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/32/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/32/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/35/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/35/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/35/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/34/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/34/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/34/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/33/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/33/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/33/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/20/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/20/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/20/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/18/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/18/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/18/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/27/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/27/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/27/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/9/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/9/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/9/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/11/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/11/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/11/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/7/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/7/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/7/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/29/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/29/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/29/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/16/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/16/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/16/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/42/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/42/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/42/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/45/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/45/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/45/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/6/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/6/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/6/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/28/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/28/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/28/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/17/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/17/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/17/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/1/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/1/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/1/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/10/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/10/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/10/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/19/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/19/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/19/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/26/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/26/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/26/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/8/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/8/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/8/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/21/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/21/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/21/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/44/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/44/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/44/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/43/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/43/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/43/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/38/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/38/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/38/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/36/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/36/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/36/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/31/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/31/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/31/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/30/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/30/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/30/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/37/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/37/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/37/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/39/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/39/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/39/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/46/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/46/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/46/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/41/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/41/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/41/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/48/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/48/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/48/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/24/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/24/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/24/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/23/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/23/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/23/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/4/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/4/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/4/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/15/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/15/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/15/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/3/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/3/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/3/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/12/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/12/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/12/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/40/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/40/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/40/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/47/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/47/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/47/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/2/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/2/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/2/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/13/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/13/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/13/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/5/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/5/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/5/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/14/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/14/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/14/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/22/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/22/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/22/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/25/results/iphone12-pixel_xl.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/25/results/iphone12-iphone12mini.arff >> ./data/dataset.unclassified.arff
tail -n +50 ../collector/log-undergrad/25/results/iphone12-iphone12max.arff >> ./data/dataset.unclassified.arff
